In [1]:
import numpy as np

In [2]:
arr1=np.array([2,4,6,8,9])

In [3]:
arr1

array([2, 4, 6, 8, 9])

In [4]:
list=[2,4,6,7,8]

In [5]:
list

[2, 4, 6, 7, 8]

In [6]:
print(arr1)

[2 4 6 8 9]


In [7]:
type(arr1)

numpy.ndarray

In [8]:
len(arr1)

5

In [9]:
arr1[0]

2

In [11]:
arr1[0:3]

array([2, 4, 6])

In [12]:
arr1[-3]

6

In [13]:
arr1

array([2, 4, 6, 8, 9])

In [14]:
arr1.shape

(5,)

In [15]:
arr1.size

5

In [16]:
arr1.ndim

1

In [19]:
arr2 =np.array([[1,2,3],[4,5,6]])

In [20]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
arr3 =np.array([[4,5,6],[7,8,9]])

In [22]:
arr3

[[4, 5, 6], [7, 8, 9]]

In [23]:
arr2.ndim

2

In [26]:
arr3.ndim

2

In [27]:
arr3.shape

(2, 3)

In [28]:
arr3.size

6

In [35]:
arr1.dtype

dtype('int64')

In [36]:
arr2.shape

(2, 3)

In [40]:
arr3 = arr2.reshape(3,2)

In [41]:
arr3.shape

(3, 2)

In [45]:
np.random.randint(4,9)

5

In [46]:
np.random.randint(0,100,5)

array([22, 40, 42, 52,  3])

In [47]:
np.random.randint(0,9,6)

array([2, 1, 1, 2, 1, 0])

In [48]:
print(np.random.randint(0,9,6))

[7 5 5 4 0 7]


In [49]:
np.random.randint(0,15,20)

array([ 2,  2,  1,  6,  2,  1,  7,  9, 10, 12,  0, 14, 13,  9,  2,  9,  7,
        7, 14,  3])

In [50]:
np.random.seed(13)
np.random.randint(0,15,20)

array([ 2,  0, 10,  0,  6,  2,  4,  9, 12, 10,  3, 10,  4, 14,  2, 14,  6,
        5, 13, 10])

In [51]:
a=np.random.randint(0,15,20)

In [53]:
a = np.sort(a)

array([ 0,  1,  2,  2,  3,  3,  4,  5,  5,  6,  8,  8,  9, 10, 11, 11, 11,
       11, 12, 12])

In [54]:
b = np.flip(a)

In [55]:
b

array([10, 12,  8, 11, 12,  8,  2,  1, 11,  5,  6, 11,  3,  5,  3,  0,  2,
        4, 11,  9])

In [57]:
np.sum(a)

134

In [58]:
np.mean(a)

6.7

In [59]:
np.unique(a)

array([ 0,  1,  2,  3,  4,  5,  6,  8,  9, 10, 11, 12])

In [61]:
np.unique(a,return_counts=True)

(array([ 0,  1,  2,  3,  4,  5,  6,  8,  9, 10, 11, 12]),
 array([1, 1, 2, 2, 1, 2, 1, 2, 1, 1, 4, 2]))

In [62]:
np.random.seed(2)
np.random.randint(0,10,6)

array([8, 8, 6, 2, 8, 7])

In [63]:
np.random.randint(0,10,(3,2))

array([[2, 1],
       [5, 4],
       [4, 5]])

In [64]:
np.random.randint(0,10,(2,3))

array([[7, 3, 6],
       [4, 3, 7]])

In [65]:
np.arange(0,10,6)

array([0, 6])

In [66]:
np.arange(0,5,1)

array([0, 1, 2, 3, 4])

In [69]:
np.arange(0,6,1).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [70]:
np.arange(3,16,4)

array([ 3,  7, 11, 15])

In [71]:
np.arange(18,5,-3)

array([18, 15, 12,  9,  6])

In [73]:
for i in range(18,5,-3):
  print(i)

18
15
12
9
6
